### ISSUE TITLE
ผลลัพธ์ไม่ถูกต้อง

### ISSUE THREAD

**Issue by brillydev** [OkveeNet/number#1]
1,111,111,111,111,213,534,876,000,111 = หนึ่งล้านหนึ่งหมื่นหนึ่งพันหนึ่งร้อยเอ็ดล้านหนึ่งแสนหนึ่งหมื่นหนึ่งร้อยสิบเอ็ดล้านหนึ่งหมื่นหนึ่งพันหนึ่งร้อยสองล้านหนึ่งแสนสามหมื่นห้าร้อยสามสิบสี่ล้านแปดหมื่นเจ็ดพันหกร้อยล้านหนึ่งร้อยสิบเอ็ดบาทถ้วน

**Comment by ve3** [comment]
คุณกรอก format number ผิดน่ะครับ
ตัวเลขนั้นแยกเป็นชุดๆ ชุดละล้าน จะได้ **111  111111  111121   353487  6000111**
อ่านว่า

>หนึ่งพันหนึ่งร้อยสิบ
>เอ็ดล้านหนึ่งแสนหนึ่งหมื่นหนึ่งพันหนึ่งร้อยสิบ
>เอ็ดล้านหนึ่งแสนหนึ่งหมื่นหนึ่งพันสองร้อยสิบ
>สามล้านห้าแสนสามหมื่นสี่พันแปดร้อยเจ็ดสิบ
>หกล้านหนึ่งร้อยสิบเอ็ด

นี่คือที่ควรจะได้ถูกไหมครับ?

อันนี้คือที่ผมทดสอบกับเครื่อง
```php
$numbers = array(
	'1111111111111213534876000111',
);

$numthai = new \Okvee\Number\NumberThai();
foreach ($numbers as $num) {
	echo $num.' = '.$numthai->convertNumber($num);
	echo '<br>';
}
```

ผลที่ได้ 

>1111111111111213534876000111 = หนึ่งพันหนึ่งร้อยสิบเอ็ดล้านหนึ่งแสนหนึ่งหมื่นหนึ่งพันหนึ่งร้อยสิบเอ็ดล้านหนึ่งแสนหนึ่งหมื่นหนึ่งพันสองร้อยสิบสามล้านห้าแสนสามหมื่นสี่พันแปดร้อยเจ็ดสิบหกล้านหนึ่งร้อยสิบเอ็ด
